import React, { useCallback, useMemo, useState } from 'react';
// 1. Import React Native components
import {
    Alert,
    AppRegistry,
    Image,
    Linking,
    Modal,
    Platform,
    Pressable,
    ScrollView,
    Text,
    TextInput,
    TouchableOpacity,
    View,
} from 'react-native';
// Community picker for dropdowns
import { Picker } from '@react-native-picker/picker';

// 2. Import React Native compatible icons
import {
    CheckCircle, FileText,
    History as HistoryIcon,
    Image as ImageIcon, Loader, Search,
    Trash2,
    Upload,
    X,
    XCircle, Zap
} from 'lucide-react-native';
// 3. Import necessary mobile utilities
import * as ImagePicker from 'expo-image-picker';
import tw from 'twrnc';

// --- Utility Data ---

const BODY_AREAS = [
    { label: 'Wrist (Carpal)', value: 'Wrist' },
    { label: 'Elbow', value: 'Elbow' },
    { label: 'Shoulder', value: 'Shoulder' },
    { label: 'Hand', value: 'Hand' },
    { label: 'Humerus (Upper Arm)', value: 'Humerus' },
];

const ABNORMALITY_TYPES = [
    { label: 'Fracture', value: 'Fracture' },
    { label: 'Tendonitis', value: 'Tendonitis' },
    { label: 'Normal/No Abnormality', value: 'Normal' },
    { label: 'Dislocation', value: 'Dislocation' },
    { label: 'Joint Fluid Accumulation', value: 'Fluid' },
];


// --- Utility Functions for API Call and UI ---

const API_KEY = ""; // Kept empty as per instructions

/**
 * Simulates the Gemini API call for multimodal generation (Image + Text).
 */
const simulateGeminiCall = async (prompt, base64ImageData, bodyArea, abnormality, modelName = 'gemini-2.5-flash-preview-09-2025') => {
    const MAX_RETRIES = 3;
    let lastError = null;

    for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
        try {
            let mockClassification, mockReportTemplate, mockConfidence;
            const randomConf = (0.85 + Math.random() * 0.1);

            if (abnormality === "Normal") {
                mockClassification = "Negative (Normal)";
                mockConfidence = (randomConf + 0.05).toFixed(2);
                mockReportTemplate = `
                    **Clinical Finding Summary:**
                    The musculoskeletal X-ray image analysis reveals a **Negative (Normal)** finding. The estimated confidence in the primary classification is ${mockConfidence * 100}%.

                    **Detailed Diagnostic Report (Generated by Multimodal T5 Transformer):**
                    The X-ray examination of the **${bodyArea}** indicates no acute osseous or soft tissue abnormalities. There is no evidence of fracture, dislocation, or significant joint effusions. The visualized skeletal structures appear intact and well-aligned.

                    **Visual Attention (Grad-CAM Simulation):**
                    The model focused predominantly on the joint spaces, confirming symmetry and integrity.

                    **Recommendation:**
                    No immediate follow-up required. Continue routine observation.
                `;
            } else {
                mockClassification = "Positive (Abnormal)";
                mockConfidence = randomConf.toFixed(2);
                
                let finding, recommendation, gradCamFocus;

                switch (abnormality) {
                    case "Fracture":
                        finding = `A linear lucency is identified in the distal **${bodyArea}**. This finding is consistent with a nondisplaced fracture. Minimal associated soft tissue swelling is noted.`;
                        recommendation = "Immediate consultation with an orthopedic specialist is recommended for further evaluation and management.";
                        gradCamFocus = `area around the fracture site, specifically segments C3-C5 of the ${bodyArea}.`;
                        break;
                    case "Tendonitis":
                        finding = `Osseous structures of the ${bodyArea} are intact. However, moderate soft tissue thickening and density are noted around the major tendons. This is suggestive of severe tendonitis or tenosynovitis.`;
                        recommendation = "Recommend clinical correlation with inflammatory markers and a follow-up ultrasound study.";
                        gradCamFocus = `soft tissue boundaries and regions adjacent to the joints in the ${bodyArea}.`;
                        break;
                    case "Dislocation":
                        finding = `There is complete loss of articulation between the primary joint surfaces of the **${bodyArea}**. The distal bone fragment is significantly displaced.`;
                        recommendation = "CRITICAL FINDING: Immediate reduction and fixation by an orthopedic surgeon required.";
                        gradCamFocus = `joint capsule where the normal anatomical alignment is disrupted.`;
                        break;
                    case "Fluid":
                        finding = `No fracture or dislocation is identified. However, there is a large collection of fluid within the joint space of the **${bodyArea}**, resulting in an increased joint capsule size. This suggests joint effusion.`;
                        recommendation = "Recommend aspiration of the joint fluid for analysis and clinical evaluation for underlying cause.";
                        gradCamFocus = `the entire joint space in the ${bodyArea}, corresponding to the increased fluid volume.`;
                        break;
                    default:
                        finding = "An unspecified abnormality was detected based on pattern analysis. Detailed investigation is required.";
                        recommendation = "Further specialized imaging (e.g., MRI) is highly recommended.";
                        gradCamFocus = "an indeterminate focal area, suggesting a complex pathology.";
                        break;
                }

                mockReportTemplate = `
                    **Clinical Finding Summary:**
                    The musculoskeletal X-ray image analysis reveals a **Positive (Abnormal)** finding (${abnormality}). The estimated confidence in the primary classification is ${mockConfidence * 100}%.

                    **Detailed Diagnostic Report (Generated by Multimodal T5 Transformer):**
                    ${finding} The bone mineral density appears adequate for the patient's age and clinical context.

                    **Visual Attention (Grad-CAM Simulation):**
                    The model focused predominantly on the ${gradCamFocus}

                    **Recommendation:**
                    ${recommendation}
                `;
            }

            // Simulate Network delay (2-5 seconds)
            await new Promise(resolve => setTimeout(resolve, 2000 + Math.random() * 3000));

            return {
                report: mockReportTemplate.trim(),
                classification: mockClassification,
                confidence: parseFloat(mockConfidence),
                sources: [
                    { uri: "https://nih.gov/radiology-standards", title: "NIH Radiology Standards (Simulated Source)" },
                    { uri: "https://stanford.edu/mura-dataset", title: "MURA Dataset Documentation (Simulated Source)" },
                ],
                // Add metadata for history
                timestamp: new Date().toLocaleTimeString(),
                bodyArea,
                abnormality,
            };

        } catch (error) {
            lastError = error;
            if (attempt < MAX_RETRIES - 1) {
                const delay = Math.pow(2, attempt) * 1000 + Math.random() * 1000;
                console.warn('Attempt ' + (attempt + 1) + ' failed. Retrying in ' + (delay / 1000) + 's...');
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        }
    }
    throw new Error(`Failed to generate content after ${MAX_RETRIES} attempts: ${lastError?.message || 'Unknown error'}`);
};

// --- New Components for Header and History ---

/**
 * Component for the History Modal
 */
const HistoryModal = ({ isVisible, onClose, history, onDeleteHistory, onSelectHistory }) => {
    return (
        <Modal
            animationType="slide"
            transparent={true}
            visible={isVisible}
            onRequestClose={onClose}
        >
            <View style={tw`flex-1 justify-end bg-black bg-opacity-50`}>
                <View style={tw`w-full h-3/4 bg-white rounded-t-xl shadow-2xl p-6`}>
                    
                    {/* Header and Close Button */}
                    <View style={tw`flex-row justify-between items-center border-b pb-3 mb-4 border-gray-200`}>
                        <Text style={tw`text-2xl font-bold text-gray-800 flex-row items-center`}>
                            <HistoryIcon style={tw`w-6 h-6 mr-2 text-indigo-500`} />
                            Analysis History
                        </Text>
                        <Pressable onPress={onClose} style={tw`p-2`}>
                            <X style={tw`w-6 h-6 text-gray-500`} />
                        </Pressable>
                        j
                    </View>

                    {/* History List */}
                    <ScrollView contentContainerStyle={tw`pb-10`}>
                        {history.length === 0 ? (
                            <View style={tw`text-center p-10`}>
                                <Text style={tw`text-gray-500`}>No history available yet. Run an analysis!</Text>
                            </View>
                        ) : (
                            history.map((item, index) => {
                                const isAbnormal = item.classification.includes('Positive');
                                const color = isAbnormal ? 'border-red-400' : 'border-green-400';

                                return (
                                    <View key={item.id || index} style={tw`flex-row justify-between items-center p-4 mb-3 border rounded-xl ${color} bg-white shadow-sm`}>
                                        <TouchableOpacity 
                                            onPress={() => onSelectHistory(item)}
                                            style={tw`flex-1 mr-3`}
                                        >
                                            <Text style={tw`text-lg font-semibold text-gray-800`}>
                                                {item.bodyArea} - {item.abnormality}
                                            </Text>
                                            <Text style={tw`text-sm text-gray-500`}>
                                                {item.classification} @ {item.timestamp}
                                            </Text>
                                        </TouchableOpacity>
                                        <TouchableOpacity 
                                            onPress={() => onDeleteHistory(item.id)}
                                            style={tw`p-2 bg-red-100 rounded-full`}
                                        >
                                            <Trash2 style={tw`w-5 h-5 text-red-600`} />
                                        </TouchableOpacity>
                                    </View>
                                );
                            })
                        )}
                    </ScrollView>
                </View>
            </View>
        </Modal>
    );
};

/**
 * Component for the fixed Header bar
 */
const Header = ({ onSearch, onShowHistory, historyCount }) => {
    const [searchText, setSearchText] = useState('');

    const handleSearch = () => {
        onSearch(searchText);
    };

    return (
        <View style={tw`bg-indigo-600 p-4 pt-8 flex-row items-center justify-between shadow-lg`}>
            
            {/* Logo/Title */}
            <Text style={tw`text-xl font-extrabold text-white`}>
                XrayApp
            </Text>

            {/* Search Bar */}
            <View style={tw`flex-row items-center flex-1 mx-4 bg-indigo-500 rounded-full p-2`}>
                <Search style={tw`w-5 h-5 text-indigo-200 ml-1`} />
                <TextInput
                    style={tw`flex-1 text-white text-sm ml-2`}
                    placeholder="Search reports..."
                    placeholderTextColor="#D1D5DB" // Tailwind gray-300
                    value={searchText}
                    onChangeText={setSearchText}
                    onSubmitEditing={handleSearch}
                    returnKeyType="search"
                />
            </View>

            {/* History Button */}
            <TouchableOpacity 
                onPress={onShowHistory} 
                style={tw`p-2 rounded-full bg-indigo-700 relative`}
            >
                <HistoryIcon style={tw`w-6 h-6 text-white`} />
                {historyCount > 0 && (
                    <View style={tw`absolute top-0 right-0 bg-red-500 rounded-full px-2`}>
                        <Text style={tw`text-xs text-white`}>{historyCount}</Text>
                    </View>
                )}
            </TouchableOpacity>
        </View>
    );
};

// --- React Native Main Component ---

const App = () => {
    const [imageFile, setImageFile] = useState(null); 
    const [imagePreviewUrl, setImagePreviewUrl] = useState('');
    const [bodyArea, setBodyArea] = useState(BODY_AREAS[0].value);
    const [abnormality, setAbnormality] = useState(ABNORMALITY_TYPES[0].value);
    const [prompt, setPrompt] = useState("Generate a comprehensive X-ray diagnostic report based on the image, focusing on abnormality detection and patient recommendations.");
    const [report, setReport] = useState(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');
    
    // History Management
    const [history, setHistory] = useState([]);
    const [isHistoryModalVisible, setIsHistoryModalVisible] = useState(false);

    const pickImage = useCallback(async () => {
        if (Platform.OS !== 'web') {
            const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
            if (status !== 'granted') {
                Alert.alert('Permission required', 'Sorry, we need camera roll permissions to make this work!');
                return;
            }
        }

        let result = await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ImagePicker.MediaTypeOptions.Images,
            allowsEditing: true,
            quality: 1,
            base64: true,
        });

        if (!result.canceled && result.assets && result.assets.length > 0) {
            const asset = result.assets[0];
            
            setImageFile(asset); 
            setImagePreviewUrl(asset.uri);
            setError('');
            setReport(null);
        } else {
            if (!result.canceled) {
                setError('Image selection failed or was cancelled.');
            }
        }
    }, []);

    const analyzeImage = useCallback(async () => {
        if (!imageFile) {
            setError('Please upload an X-ray image first.');
            return;
        }
        
        if (!imageFile.base64) {
            setError('Failed to retrieve base64 image data.');
            return;
        }

        setIsLoading(true);
        setError('');
        setReport(null);

        try {
            const base64Data = imageFile.base64;
            
            // Generate Report
            const result = await simulateGeminiCall(prompt, base64Data, bodyArea, abnormality);
            
            setReport(result);
            
            // Add new report to history
            setHistory(prevHistory => [{ 
                ...result, 
                id: Date.now(), // Unique ID for deletion
                imageUri: imagePreviewUrl,
            }, ...prevHistory]);

        } catch (err) {
            console.error(err);
            setError(err.message || 'An error occurred during analysis.');
        } finally {
            setIsLoading(false);
        }
    }, [imageFile, prompt, bodyArea, abnormality, imagePreviewUrl]); 

    // Delete history entry by ID
    const handleDeleteHistory = useCallback((id) => {
        Alert.alert(
            "Confirm Delete",
            "Are you sure you want to delete this history item?",
            [
                {
                    text: "Cancel",
                    style: "cancel"
                },
                { 
                    text: "Delete", 
                    onPress: () => setHistory(prevHistory => prevHistory.filter(item => item.id !== id)),
                    style: "destructive"
                }
            ],
            { cancelable: true }
        );
    }, []);

    // Load a history entry as the current report
    const handleSelectHistory = useCallback((item) => {
        setReport(item);
        setImagePreviewUrl(item.imageUri || ''); // Display the image used for this report if available
        setBodyArea(item.bodyArea);
        setAbnormality(item.abnormality);
        setIsHistoryModalVisible(false); // Close modal
        // Alert.alert('History Loaded', `Report for ${item.bodyArea} loaded successfully.`);
    }, []);

    // Handle search (currently simulated)
    const handleSearch = useCallback((searchText) => {
        Alert.alert('Search Feature', `Simulated search for: "${searchText}". In a real app, this would filter the history or search a database.`);
    }, []);

    const ClassificationBox = useMemo(() => {
        if (!report) return null;

        const { classification, confidence } = report;
        const isAbnormal = classification.includes('Positive');
        const icon = isAbnormal ? XCircle : CheckCircle; 
        const color = isAbnormal ? 'bg-red-100 text-red-800 border-red-400' : 'bg-green-100 text-green-800 border-green-400';
        const label = isAbnormal ? 'ABNORMAL FINDING' : 'NORMAL FINDING';

        return (
            <View style={tw`p-4 rounded-lg shadow-md border-l-4 ${color} mb-6`}>
                <View style={tw`flex-row items-center space-x-3`}>
                    {React.createElement(icon, { style: tw`w-6 h-6` })}
                    <Text style={tw`text-lg font-bold uppercase ${color.split(' ')[1]}`}>{label}</Text>
                </View>
                <View style={tw`mt-2`}>
                    <Text style={tw`text-sm ${color.split(' ')[1]}`}>
                        Primary Classification: <Text style={tw`font-bold`}>{classification}</Text>
                    </Text>
                    <Text style={tw`text-sm ${color.split(' ')[1]}`}>
                        Model Confidence: <Text style={tw`font-bold`}>{(confidence * 100).toFixed(1)}%</Text>
                    </Text>
                </View>
            </View>
        );
    }, [report]);

    return (
        <View style={tw`flex-1`}>
            {/* --- FIXED HEADER --- */}
            <Header 
                onSearch={handleSearch} 
                onShowHistory={() => setIsHistoryModalVisible(true)}
                historyCount={history.length}
            />
            
            <ScrollView contentContainerStyle={tw`min-h-full bg-gray-50 p-4 sm:p-8 font-sans`}>
                
                {/* --- Main Title (Below Header) --- */}
                <View style={tw`text-center mb-10 mt-4`}>
                    <Text style={tw`text-3xl sm:text-4xl font-extrabold text-gray-900 mb-2 tracking-tight text-center`}>
                        <Zap style={tw`w-8 h-8 mr-2 text-indigo-500`} />
                        Automated X-ray Diagnostic System
                    </Text>
                    <Text style={tw`text-lg text-gray-600 text-center`}>
                        Multimodal AI (Vision + Language) for Real-Time Radiographic Reporting.
                    </Text>
                </View>

                {/* --- Input Panel & Report Panel Container --- */}
                <View style={tw`flex-1 lg:flex-row gap-8`}>
                    {/* --- Input Panel (Left) --- */}
                    <View style={tw`lg:w-1/3 w-full bg-white p-6 rounded-xl shadow-2xl border border-gray-100 mb-8 lg:mb-0`}>
                        <Text style={tw`text-xl font-semibold text-gray-800 mb-4 flex-row items-center space-x-2`}>
                            <Upload style={tw`w-5 h-5 text-indigo-500`} />
                            <Text>Input X-ray Image</Text>
                        </Text>
                        
                        {/* 1. Image Upload Area */}
                        <View style={tw`mb-6`}>
                            <Text style={tw`block text-sm font-medium text-gray-700 mb-2`}>1. Upload Image (PNG/JPEG)</Text>
                            
                            <TouchableOpacity 
                                onPress={pickImage}
                                style={tw`w-full py-3 px-4 rounded-xl font-bold transition duration-300 shadow-lg flex-row items-center justify-center space-x-2 bg-indigo-600 hover:bg-indigo-700`}
                            >
                                <Upload style={tw`w-5 h-5 text-white`} />
                                <Text style={tw`text-white font-bold`}>Select Image from Library</Text>
                            </TouchableOpacity>
                        </View>

                        {/* Image Preview */}
                        <View style={tw`aspect-square w-full bg-gray-100 rounded-lg flex items-center justify-center border-4 border-dashed border-gray-300 overflow-hidden shadow-inner mb-6`}>
                            {imagePreviewUrl ? (
                                <Image
                                    source={{ uri: imagePreviewUrl }}
                                    style={tw`w-full h-full`}
                                    resizeMode="contain"
                                />
                            ) : (
                                <View style={tw`text-center p-4`}>
                                    <ImageIcon style={tw`w-10 h-10 mx-auto mb-2 text-gray-500`} />
                                    <Text style={tw`text-gray-500`}>Image preview will appear here.</Text>
                                    <Text style={tw`text-xs mt-1 text-gray-400`}>(Simulated MURA dataset image)</Text>
                                </View>
                            )}
                        </View>

                        {/* 2. Dropdown for Body Area */}
                        <View style={tw`mt-2`}>
                            <Text style={tw`block text-sm font-medium text-gray-700 mb-2`}>2. Area of Body</Text>
                            <View style={tw`border border-gray-300 rounded-lg overflow-hidden bg-white`}>
                                <Picker
                                    selectedValue={bodyArea}
                                    onValueChange={(itemValue) => setBodyArea(itemValue)}
                                    style={tw`w-full h-12`}
                                    itemStyle={tw`text-sm`}
                                >
                                    {BODY_AREAS.map(item => (
                                        <Picker.Item key={item.value} label={item.label} value={item.value} />
                                    ))}
                                </Picker>
                            </View>
                        </View>

                        {/* 3. Dropdown for Abnormality Type */}
                        <View style={tw`mt-4`}>
                            <Text style={tw`block text-sm font-medium text-gray-700 mb-2`}>3. Abnormality Type (Simulated)</Text>
                            <View style={tw`border border-gray-300 rounded-lg overflow-hidden bg-white`}>
                                <Picker
                                    selectedValue={abnormality}
                                    onValueChange={(itemValue) => setAbnormality(itemValue)}
                                    style={tw`w-full h-12`}
                                    itemStyle={tw`text-sm`}
                                >
                                    {ABNORMALITY_TYPES.map(item => (
                                        <Picker.Item key={item.value} label={item.label} value={item.value} />
                                    ))}
                                </Picker>
                            </View>
                        </View>


                        {/* 4. Prompt Input */}
                        <View style={tw`mt-6`}>
                            <Text style={tw`block text-sm font-medium text-gray-700 mb-2 flex-row items-center space-x-1`}>
                                <Search style={tw`w-4 h-4`} />
                                <Text>4. Analysis Prompt</Text>
                            </Text>
                            <TextInput
                                id="prompt"
                                value={prompt}
                                onChangeText={setPrompt}
                                multiline
                                numberOfLines={3}
                                style={tw`w-full p-3 border border-gray-300 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 text-sm`}
                                placeholder="E.g., Focus on joint space narrowing..."
                            />
                        </View>

                        {/* Analyze Button */}
                        <TouchableOpacity
                            onPress={analyzeImage}
                            disabled={isLoading || !imageFile}
                            style={tw`w-full py-3 px-4 rounded-xl font-bold transition duration-300 shadow-lg flex-row items-center justify-center space-x-2 ${
                                isLoading || !imageFile ? 'bg-indigo-300' : 'bg-indigo-600 hover:bg-indigo-700'
                            } mt-4`}
                        >
                            {isLoading ? (
                                <>
                                    <Loader style={tw`w-5 h-5 animate-spin text-white`} />
                                    <Text style={tw`text-white`}>Analyzing... (Simulating Multimodal Pipeline)</Text>
                                </>
                            ) : (
                                <>
                                    <Zap style={tw`w-5 h-5 text-white`} />
                                    <Text style={tw`text-white`}>Run Diagnostic Analysis</Text>
                                </>
                            )}
                        </TouchableOpacity>

                        {error && <View style={tw`bg-red-100 border border-red-400 px-4 py-3 rounded-xl mt-4`}><Text style={tw`text-red-700`}>{error}</Text></View>}
                    </View>

                    {/* --- Report Panel (Right) --- */}
                    <View style={tw`lg:w-2/3 w-full bg-white p-6 rounded-xl shadow-2xl border border-gray-100`}>
                        <Text style={tw`text-xl font-semibold text-gray-800 mb-4 flex-row items-center space-x-2`}>
                            <FileText style={tw`w-5 h-5 text-indigo-500`} />
                            <Text>Generated Diagnostic Report</Text>
                        </Text>

                        {/* Classification Summary */}
                        {ClassificationBox}

                        {/* Report Output */}
                        <View style={tw`min-h-[400px] bg-gray-50 p-5 rounded-lg border border-gray-200 overflow-y-auto`}>
                            {report ? (
                                <ScrollView>
                                    <View style={tw`max-w-none text-gray-800`}>
                                        <Text style={tw`text-lg font-bold mb-3 text-indigo-700`}>AI-Generated Report Details:</Text>
                                        
                                        <Text>
                                            {report.report
                                                .split('\n')
                                                .filter(line => line.trim() !== '')
                                                .map((line, index) => {
                                                    const parts = line.split(/(\*\*.*?\*\*)/g).map((part, pIndex) => {
                                                        if (part.startsWith('**') && part.endsWith('**')) {
                                                            return <Text key={pIndex} style={tw`font-bold`}>{part.slice(2, -2)}</Text>;
                                                        }
                                                        return part;
                                                    });
                                                    
                                                    return (
                                                        <Text key={index} style={tw`mb-2`}>
                                                            {parts}
                                                            {"\n\n"}
                                                        </Text>
                                                    );
                                                })
                                            }
                                        </Text>
                                    </View>
                                    <View style={tw`mt-6 pt-4 border-t border-gray-200`}>
                                        <Text style={tw`text-sm font-semibold text-gray-700 mb-2`}>Sources (Simulated Grounding Metadata):</Text>
                                        <View style={tw`list-disc list-inside space-y-1 text-sm text-gray-600`}>
                                            {report.sources.map((source, index) => (
                                                <TouchableOpacity 
                                                    key={index} 
                                                    onPress={() => Linking.openURL(source.uri)}
                                                    style={tw`mt-1`}
                                                >
                                                    <Text style={tw`text-indigo-600 underline`}>
                                                        {source.title}
                                                    </Text>
                                                </TouchableOpacity>
                                            ))}
                                        </View>
                                    </View>
                                </ScrollView>
                            ) : isLoading ? (
                                <View style={tw`text-center p-12 text-gray-500`}>
                                    <Loader style={tw`w-8 h-8 mx-auto mb-3 animate-spin text-indigo-500`} />
                                    <Text style={tw`font-semibold`}>Processing image and generating report...</Text>
                                    <Text style={tw`text-sm`}>Please wait, this simulates a complex AI analysis.</Text>
                                </View>
                            ) : (
                                <View style={tw`text-center p-12 text-gray-500`}>
                                    <FileText style={tw`w-10 h-10 mx-auto mb-3`} />
                                    <Text>Upload an X-ray and click "Run Diagnostic Analysis" to generate a report here.</Text>
                                </View>
                            )}
                        </View>
                    </View>
                </View>

                {/* --- Footer --- */}
                <View style={tw`mt-10 text-center text-sm text-gray-500 border-t pt-6`}>
                    <Text style={tw`text-center text-sm text-gray-500`}>Simulated Multimodal AI Pipeline using React Native and Expo. All diagnostic results are illustrative.</Text>
                </View>
            </ScrollView>

            {/* --- HISTORY MODAL --- */}
            <HistoryModal
                isVisible={isHistoryModalVisible}
                onClose={() => setIsHistoryModalVisible(false)}
                history={history}
                onDeleteHistory={handleDeleteHistory}
                onSelectHistory={handleSelectHistory}
            />
        </View>
    );
};


// Fix: Explicitly register the main application component.
AppRegistry.registerComponent('main', () => App);
export default App;
AppRegistry.registerComponent('main', () => App);App;